
---
log_level: "INFO"
credit_card_fraud:
  enable: true
  data_download : false
  data_handle: "mlg-ulb/creditcardfraud"
  data_folder: "creditcardfraud"
  job_config:
    cluster_list: [2, 5, 10] #[2, 5, 10]